services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/src/.env